export enum Actions {
  SET_COLUMNID = 'SET_COLUMNID',
  SET_COLUMNTITLE = 'SET_COLUMNTITLE',
  SET_COLUMNLIST = 'SET_COLUMNLIST',
  EDIT_COLUMNTITLE = 'EDIT_COLUMNTITLE',
  REMOVE_COLUMN = 'REMOVE_COLUMN',
  SET_TASKID = 'SET_TASKID',
  SET_TASKTITLE = 'SET_TASKTITLE',
  SET_TASKDESCR = 'SET_TASKTITLE',
  SET_TASKLIST = 'SET_TASKLIST',
}

export enum DialogForm {
  login = 'login',
  register = 'registration',
}

export enum ActionsCalendar {
  SET_CURRENTDATE = 'SET_CURRENTDATE',

  GET_TASKS = 'GET_TASKS',
  EDIT_TASK = 'EDIT_TASK',
  REMOVE_TASK = 'REMOVE_TASK',
  ADD_TASK = 'ADD_TASK',
}
